version: "3"
services:
  selenium_chrome:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "127.0.0.1:4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped